=== 131/yks/rsrcs/dtds/myks.dtd
<!ENTITY % MYKSEntities PUBLIC "-//YKS//MYKSEntities" "sql_entities.dtd">
%MYKSEntities;
<!ENTITY % MYKSProcedures PUBLIC "-//YKS//MYKSProcedures" "sql_procedures.dtd">
<!ENTITY % MYKSViews PUBLIC "-//YKS//MYKSViews" "sql_views.dtd">

<!ELEMENT myks (mykse|table|procedure|view)+>

<!ELEMENT mykse ( description?,(%mykses;)?)>

<!ELEMENT table ( description?, fields+)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT def (#PCDATA)>

<!ATTLIST table
  name	CDATA	#REQUIRED
  %block;
>
<!ENTITY % fk_actions "(cascade|set_null|no_action)">

<!ELEMENT fields (field+)>

<!ELEMENT field EMPTY>
<!ATTLIST field
  type	CDATA	#REQUIRED
  name	CDATA	#IMPLIED
  key   CDATA  #IMPLIED
  extra (auto_increment) #IMPLIED
  default CDATA	#IMPLIED
  update %fk_actions; 'cascade'
  delete %fk_actions; 'no_action'
  defer (defer|strict) 'defer'
>


<!ATTLIST mykse
  type  CDATA	#REQUIRED
  birth	CDATA	#IMPLIED
  default CDATA	#IMPLIED
  %null;
  %block;
>


%MYKSProcedures;
%MYKSViews;

=== 131/yks/3rd/worker/myks/history.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_jobs_history">
    <fields>
      <field type="job_id" delete="cascade"/>
      <field type="job_state"/>
      <field type="job_time"/>
      <field type="worker_id" null="null"/>
    </fields>
  </table>
  <mykse type="job_time">
    <int size="float"/>
  </mykse>
</myks>

=== 131/yks/3rd/localization/myks/tags.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_locale_tags_list">
    <fields>
      <field type="locale_tag" name="tag_id" key="primary"/>
      <field type="locale_tag" name="parent_tag"/>
      <field type="title" name="tag_name"/>
      <field type="project_id"/>
<!-- le prefix est affichÃ© comme valeur par default dans le nom des items
qu'on ajouterai sur ce tag-->
      <field type="title" name="tag_prefix"/>
    </fields>
  </table>
  <mykse type="locale_tag" null="null" birth="ks_locale_tags_list">
    <int/>
  </mykse>
  <table name="ks_locale_tag_items">
    <fields>
      <field type="locale_tag" name="tag_id"/>
      <field type="item_key" delete="cascade"/>
    </fields>
  </table>
</myks>

=== 131/yks/base/myks/yks/locale/base.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_locale_values">
    <fields>
      <field type="item_key" key="primary" delete="cascade"/>
      <field type="lang_key" key="primary"/>
      <field type="text" name="value"/>
    </fields>
  </table>
  <mykse type="item_key">
    <string length="128"/>
  </mykse>
</myks>

=== 131/yks/base/myks/yks/locale/titles.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_myks_titles">
    <fields>
      <field type="myks_type" key="primary"/>
      <field type="myks_val" key="primary"/>
      <field type="lang_key" key="primary"/>
      <field type="trad"/>
    </fields>
  </table>
  <mykse type="trad">
    <string length="200"/>
  </mykse>
  <mykse type="myks_val">
    <string length="20"/>
  </mykse>
</myks>

=== 131/yks/3rd/geomaps/myks/main.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_geomaps_area_list">
    <fields>
      <field type="area_id"/>
      <field type="area_key"/>
      <field type="title" name="area_name"/>
    </fields>
  </table>
  <mykse type="area_id" birth="ks_geomaps_area_list">
    <string length="50"/>
  </mykse>
  <mykse type="area_key">
    <string length="20"/>
  </mykse>
  <table name="ks_users_geomaps_list">
    <fields>
      <field type="map_id"/>
      <field type="title" name="map_name"/>
      <field type="user_id"/>
    </fields>
  </table>
  <mykse type="map_id" birth="ks_users_geomaps_list">
    <int/>
  </mykse>
  <table name="ks_users_geomaps_area">
    <fields>
      <field type="map_id"/>
      <field type="area_id"/>
      <field type="user_id"/>
    </fields>
  </table>
</myks>

=== 131/yks/rsrcs/myks/yks/users/auth/password.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_auth_password">
    <fields>
      <field type="user_id" key="primary" update="cascade" delete="cascade"/>
      <field type="user_login" key="unique"/>
      <field type="user_pswd"/>
    </fields>
  </table>
  <mykse type="user_pswd">
    <mykse type="sha1"/>
  </mykse>
  <mykse type="user_login">
    <mykse type="user_name"/>
  </mykse>
</myks>

=== 131/yks/base/myks/isos/639.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="iso_639_languages">
    <fields>
      <field type="lang_code"/>
      <field type="title" name="lang_name"/>
      <field type="lang_code" name="alpha_3"/>
      <field type="lang_code_alpha2" name="alpha_2"/>
    </fields>
  </table>
  <mykse type="lang_code" birth="iso_639_languages">
    <string length="3"/>
  </mykse>
  <mykse type="lang_code_alpha2" null="null">
    <string length="2"/>
  </mykse>
</myks>
