=== 131/yks/rsrcs/dtds/myks.dtd
<!ENTITY % MYKSEntities PUBLIC "-//YKS//MYKSEntities" "sql_entities.dtd">
%MYKSEntities;
<!ENTITY % MYKSProcedures PUBLIC "-//YKS//MYKSProcedures" "sql_procedures.dtd">
<!ENTITY % MYKSViews PUBLIC "-//YKS//MYKSViews" "sql_views.dtd">

<!ELEMENT myks (mykse|table|procedure|view)+>

<!ELEMENT mykse ( description?,(%mykses;)?)>

<!ELEMENT table ( description?, fields+)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT def (#PCDATA)>

<!ATTLIST table
  name	CDATA	#REQUIRED
  %block;
>
<!ENTITY % fk_actions "(cascade|set_null|no_action)">

<!ELEMENT fields (field+)>

<!ELEMENT field EMPTY>
<!ATTLIST field
  type	CDATA	#REQUIRED
  name	CDATA	#IMPLIED
  key   CDATA  #IMPLIED
  extra (auto_increment) #IMPLIED
  default CDATA	#IMPLIED
  update %fk_actions; 'cascade'
  delete %fk_actions; 'no_action'
  defer (defer|strict) 'defer'
>


<!ATTLIST mykse
  type  CDATA	#REQUIRED
  birth	CDATA	#IMPLIED
  default CDATA	#IMPLIED
  %null;
  %block;
>


%MYKSProcedures;
%MYKSViews;

=== 131/yks/rsrcs/myks/yks/locale/main.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_languages">
    <fields>
      <field type="lang_key"/>
      <field type="country_code"/>
      <field type="lang_code"/>
      <field type="lang_key" name="lang_fallback"/>
      <field type="title" name="lang_name"/>
    </fields>
  </table>
  <mykse type="lang_key" birth="ks_languages" default="'en-us'">
    <string length="5"/>
  </mykse>
</myks>

=== 131/yks/3rd/base/myks/yks/history/main.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="zks_deletion_history">
    <fields>
      <field type="zks_deletion_id"/>
      <field type="user_id"/>
      <field type="title" name="mykse_type"/>
      <field type="now" name="deletion_time"/>
      <field type="deletion_reason"/>
      <field type="deletion_blob"/>
    </fields>
  </table>
  <mykse type="zks_deletion_id" birth="zks_deletion_history">
    <int/>
  </mykse>
  <mykse type="deletion_reason">
    <string length="255"/>
  </mykse>
  <mykse type="deletion_blob">
    <text/>
  </mykse>
</myks>

=== 131/yks/3rd/talks/myks/main.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_talks_list">
    <fields>
      <field type="talk_id"/>
      <field type="user_id"/>
      <field type="now" name="talk_date"/>
      <field type="count" name="talk_weight"/>
    </fields>
    <trigger on="delete" timing="before">
BEGIN
DELETE FROM `ks_talks_tree` WHERE talk_id = OLD.talk_id;
END;
    </trigger>
  </table>
  <table name="ks_talks_contents">
    <fields>
      <field type="talk_id" delete="cascade"/>
      <field type="title" name="talk_title"/>
      <field type="talk_content" null="null"/>
    </fields>
  </table>
  <mykse type="talk_id" birth="ks_talks_list">
    <int/>
  </mykse>
  <mykse type="talk_content">
    <text/>
  </mykse>
</myks>

=== 131/yks/base/myks/yks/thoughts/main.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_toughts_list">
    <fields>
      <field type="thought_id"/>
      <field type="user_id"/>
      <field type="thought_msg"/>
      <field type="thought_date"/>
    </fields>
  </table>
  <mykse type="thought_id" birth="ks_toughts_list">
    <int/>
  </mykse>
  <mykse type="thought_msg">
    <string length="250"/>
  </mykse>
  <mykse type="thought_date">
    <mykse type="time"/>
  </mykse>
</myks>

=== 131/yks/3rd/localization/myks/languages_last_update.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_languages_last_update">
    <fields>
      <field type="lang_key"/>
      <field type="update_date"/>
      <field type="generation_date"/>
    </fields>
  </table>

  <mykse type="generation_date" null="null">
    <int size="big"/>
  </mykse>
  <mykse type="update_date" null="null">
    <int size="big"/>
  </mykse>
</myks>

=== 131/yks/3rd/localization/myks/sshot.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_locale_tags_list">
    <fields>
      <field type="sshot_coords" name="sshot_width"/>
      <field type="sshot_coords" name="sshot_height"/>
    </fields>
  </table>
  <mykse type="sshot_coords" null="null">
    <int/>
  </mykse>
  <mykse type="locale_tag" birth="ks_locale_tags_list">
    <int/>
  </mykse>
  <table name="ks_locale_tag_items">
    <fields>
      <field type="sshot_coords" name="item_x"/>
      <field type="sshot_coords" name="item_y"/>
      <field type="sshot_coords" name="item_w"/>
      <field type="sshot_coords" name="item_h"/>
    </fields>
  </table>
</myks>

=== 131/yks/3rd/shop/myks/products_categ.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_shop_categories_list">
    <fields>
      <field type="category_id"/>
      <field type="category_parent" delete="cascade"/>
    </fields>
  </table>
  <table name="ks_shop_products_categories">
    <fields>
      <field type="product_id" key="primary" delete="cascade"/>
      <field type="category_id" key="primary" delete="cascade"/>
    </fields>
  </table>
  <mykse type="category_id" birth="ks_shop_categories_list">
    <string length="25"/>
  </mykse>
  <mykse type="category_parent" null="null">
    <mykse type="category_id"/>
  </mykse>
</myks>

=== 131/yks/3rd/localization/myks/languages.xml
<?xml version="1.0"?>
<!DOCTYPE myks PUBLIC  "-//YKS//MYKS" "http://rsrcs.exyks.org/dtds/myks.dtd">
<myks>
  <table name="ks_locale_languages">
    <fields>
      <field type="lang_key"/>
      <field type="country_code"/>
      <field type="lang_code"/>
      <field type="lang_key" name="lang_fallback"/>
      <field type="title" name="lang_name"/>
      <field type="locale_domain_id"/>
    </fields>
  </table>
  <mykse type="lang_key" birth="ks_locale_languages" default="'en-us_1'">
    <string length="10"/>
  </mykse>
</myks>
